### PR TITLE
Programmatic control

### PR DESCRIPTION
**Pull request by sickill**
This brings back programmatic control from v2.

```javascript
const player = AsciinemaPlayer.create(url, containerElement);

player.addEventListener('pause', () => {
  console.log("paused!");
})

player.play().then(() => {
  console.log(`started! duration: ${player.getDuration()}`);
});
```

### CODE REVIEW

**Comment by pocek** [comment]
Is it possible to get asciicast metadata from the player object? Specifically any custom metadata, environment variables, title, etc.?

**Comment by sickill** [comment]
Not at the moment. This data is not currently extracted from the asciicast file by the JS player as there was no need for that. What's your use case?

**Comment by pocek** [comment]
Well, in addition to the title, I store some extra metadata in the asciicast I would want to show on a page along the player. I would like to avoid loading the JSON on my own just to extract the info. It's weirdly missing bit of functionality IMO - one can store title, env vars with `asciinema rec` and even other metadata with the asciinema API, but cannot access it in the player. Sorry if this is getting a little bit off-topic for this PR.

**Comment by sickill** [comment]
I get your point, that's a useful perspective. I'm wrapping up 3.0 now and I don't want to add more new stuff to it at this point but I think exposing the metadata in one of the follow up releases (3.1+) is definitely something we can do :+1:

**Pull request merged**
