### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jessp01**
Great project. This pull fixes some minor README typos.

PS
I was pondering extending the solution so that you could overlay video bits over the div of the ASCIInema player so one can toggle between views (the text from the `cast` file and video segments). This will provide the ultimate solution to tutorials that require both shell work and screen display - GUI IDE, browser, whatnot). I was wondering whether this was previously considered/worked on?

Cheers,

### CODE REVIEW

**Comment by sickill** [comment]
Thanks!

Re overlaying video: that's not planned, not really in scope of this project. Interesting idea though. I think best would be to build some higher level component which would embed both asciinema player and the video element, and switch between them.

**Comment by jessp01** [comment]
Hi @sickill ,

Yes, I agree. I'll give it a go and share the results with you. May I also ask, have you considered adding search functionality to `asciinema-server`? I think it would greatly help with discovering content. Another thought I had is adding the number of views to the cast previews.

**Comment by sickill** [comment]
Full-text search is definitely something I plan to add, just haven't gotten to it yet.

And displaying number of views on preview cards is excellent idea :ok_hand:

**Comment by jessp01** [comment]
I'll try to allocate some time to help with these:)
Also, I submitted this pull request: https://github.com/cookpete/react-player/pull/1653

`ReactPlayer` is used in many different projects/platforms so supporting `asciinema` will hopefully help to increase adoption.

**Pull request merged**
