### PR TITLE
Add package.json for use with npm

### LINKED ISSUE #54: Add a way to use asciinema-player with a package manager
Is there a way to use a package manager (such as bower) for asciinema-player to keep an updated version and avoid versioning a vendor?

### PR DESCRIPTION
**Pull request by sanand0**
Fixes #54.

This is based on #92 by @SkypLabs

### CODE REVIEW

**Comment by sanand0** [comment]
`jdk: oraclejdk10` is deprecated on Travis CI. I've switched to `openjdk10` instead. This requires [swapping SSL certificates](https://www.deps.co/guides/travis-ci-latest-java/) -- which is part of this PR as well.

I've also taken the liberty of publishing this at https://www.npmjs.com/package/asciinema-player and will add all maintainers as admin

**Comment by sickill** [comment]
Glad you figured out the SSL certs issue 🏆 . I tried with openjdk not long ago, but hit this problem and reverted to Oracle's one. 👍 

I'll deal with #92 first, and then merge this.

**Comment by sickill** [comment]
Thanks!

**Comment by sickill** [comment]
@sanand0 can you add me (user "sickill") as admin on npmjs.org, so I can publish?

**Comment by sanand0** [comment]
@sickill -- done!

**Pull request merged**
